#!/bin/bash 
#
# Starts up pgpool in a screen session 
#

LOG_FILE="/var/log/pgpool.log"

if [ ! $USER = "root" ]; then
	echo "This must be run as root"
	exit 1
fi

STARTUP_MESSAGE=$(cat <<EOT

Starting pgpool `date +%Y-%m-%d\ %H:%M:%S`
 

EOT
)

echo -e "$STARTUP_MESSAGE" | tee -a "$LOG_FILE"

pgpool -n | tee -a "$LOG_FILE"

