#!/bin/bash 
#
# Starts up pgpool in a screen session 
#

LOG_FILE="/var/log/pgpool.log"
PGPOOL="/usr/local/bin/pgpool"
RUN_DIR="/var/run/pgpool/"

STARTUP_MESSAGE=$(cat <<EOT

Starting pgpool `date +%Y-%m-%d\ %H:%M:%S`


EOT
)

if [ ! $USER = "root" ]; then
	echo "This must be run as root"
	exit 1
fi


echo -e "$STARTUP_MESSAGE\n" | tee -a "$LOG_FILE"

# Make sure the run directory exists 
if [ ! -e "$RUN_DIR" ]; then 
	mkdir -p "$RUN_DIR"
	chown blabcake:blabcake /var/run/pgpool
fi

"$PGPOOL" -n | tee -a "$LOG_FILE"

